version: 2
jobs:
  build:
    docker:
      - image: yamaza520s/circleci-awscli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run register
          no_output_timeout: 1.5h
          command: |
            sh docker-registry-ecr.sh
workflows:
  version: 2
  dev:
    jobs:
      - build:
          filters:
            branches:
              only: master
