version: 2
jobs:
  dev-build:
    docker:
      - image: yamaza520s/circleci-awscli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run register
          no_output_timeout: 1.5h
          command: |
            sh build-dev.sh
  prd-build:
    docker:
      - image: yamaza520s/circleci-awscli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run register
          no_output_timeout: 1.5h
          command: |
            sh build-prd.sh
workflows:
  version: 2
  dev:
    jobs:
      - dev-build:
          filters:
            branches:
              only: develop
  prd:
    jobs:
      - prd-build:
          filters:
            branches:
              only: master
            tags:
              only: /^3.*/
