# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: yamaza520s/circleci-awscli
    branches:
      ignore:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run register
          no_output_timeout: 1.5h
          command: |
            sh docker-registry-ecr.sh
workflows:
  version: 2
  plan:
    jobs:
      - build:
          filters:
            branches:
              only: /feature\/.*/
